name: Add Label

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string

env:
  UBUNTU_VERSION: '22.04'
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  add-label:
    runs-on: ubuntu-${{ env.UBUNTU_VERSION }}
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['${{ inputs.label }}']
              });
              console.log('Label added successfully');
            } catch (error) {
              console.error('Error adding label:', error.message);
            }
