name: Add Label

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string
    secrets:
      UBUNTU_VERSION:
        required: true
      NODE_VERSION:
        required: true
      PNPM_VERSION:
        required: true

jobs:
  add-label:
    runs-on: ubuntu-${{ secrets.UBUNTU_VERSION }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ secrets.PNPM_VERSION }}

      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['${{ inputs.label }}']
              });
              console.log('Label added successfully');
            } catch (error) {
              console.error('Error adding label:', error.message);
            }
