name: Add Label

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string
      ubuntu_version:
        required: true
        type: string
      node_version:
        required: true
        type: string
      pnpm_version:
        required: true
        type: string

jobs:
  add-label:
    runs-on: ubuntu-${{ inputs.ubuntu_version }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ inputs.pnpm_version }}

      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['${{ inputs.label }}']
              });
              console.log('Label added successfully');
            } catch (error) {
              console.error('Error adding label:', error.message);
            }
