name: Add Label

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['${{ inputs.label }}']
              });
              console.log('Label added successfully');
            } catch (error) {
              console.error('Error adding label:', error.message);
            }
