name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  env:
    uses: spences10/modular-workflow/.github/workflows/env.yml@main

  process-pr:
    if: github.event_name == 'pull_request'
    uses: spences10/modular-workflow/.github/workflows/add-label.yml@main
    with:
      label: 'needs-review'
