name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UBUNTU_VERSION: '22.04'
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  process-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/add-label.yml
    with:
      label: 'needs-review'
      ubuntu_version: ${{ env.UBUNTU_VERSION }}
