name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-pr:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/add-label.yml
    with:
      label: 'needs-review'
    env:
      UBUNTU_VERSION: ${{ secrets.UBUNTU_VERSION }}
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      PNPM_VERSION: ${{ secrets.PNPM_VERSION }}
